/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package percobaan9;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author ferdian
 */
public class Beli_Stock_Bunga extends javax.swing.JFrame {

    /**
     * Creates new form Beli_Stock_Bunga
     */
    public Beli_Stock_Bunga() {
        initComponents();
        populateComboBoxBunga();
    populateComboBoxPemasok();
    setTanggalOtomatis();
    loadDataPembelian();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHapusBunga = new javax.swing.JButton();
        cbNamaPemasok = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        spJumlahBunga = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        CbBunga = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPesanan = new javax.swing.JTable();
        txtTanggal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPembelian = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtTotalHarga = new javax.swing.JTextField();
        btnTambahBunga = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnSimpanPembelian = new javax.swing.JButton();
        btnBatalPembelian = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHapusBunga.setText("Hapus Bunga");
        btnHapusBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusBungaActionPerformed(evt);
            }
        });

        cbNamaPemasok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbNamaPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNamaPemasokActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setText("FRAME PEMNYETOKAN  BUNGA");

        jLabel3.setText("Nama Pemasok");

        CbBunga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbBungaActionPerformed(evt);
            }
        });

        jLabel4.setText("Tanggal pesanan");

        tblPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "ID Pesanan", "Nama Customer", "Tanggal Pesanan", "Nama Bunga", "Jumlah Bunga", "Harga per Bunga", "Total Harga" // Nama kolom
            }
        ));
        jScrollPane2.setViewportView(tblPesanan);

        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });

        jLabel8.setText("Tabel pembelian");

        jLabel2.setText("jumlah");

        TblPembelian.setBackground(new java.awt.Color(102, 102, 255));
        TblPembelian.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        TblPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String[]{"Pembelian ID", "Supplier ID", "Tanggal", "Total Harga"}
        ));
        jScrollPane1.setViewportView(TblPembelian);

        jLabel5.setText("Nama Bunga");

        txtTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalHargaActionPerformed(evt);
            }
        });

        btnTambahBunga.setText("Tambah Bunga");
        btnTambahBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBungaActionPerformed(evt);
            }
        });

        jLabel9.setText("Total Harga");

        btnSimpanPembelian.setText("Simpan Pembelian");
        btnSimpanPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPembelianActionPerformed(evt);
            }
        });

        btnBatalPembelian.setText("Batal Pembelian");
        btnBatalPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalPembelianActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel5)))
                                .addGap(18, 18, 18)
                                .addComponent(CbBunga, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spJumlahBunga, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbNamaPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTambahBunga)
                .addGap(32, 32, 32)
                .addComponent(btnHapusBunga)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnSimpanPembelian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBatalPembelian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNamaPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbBunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(spJumlahBunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahBunga)
                    .addComponent(btnHapusBunga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanPembelian)
                    .addComponent(btnBatalPembelian)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusBungaActionPerformed
        int selectedRow = tblPesanan.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) tblPesanan.getModel();
            double subtotal = (double) model.getValueAt(selectedRow, 6);
            double totalHarga = Double.parseDouble(txtTotalHarga.getText());
            totalHarga -= subtotal;
            txtTotalHarga.setText(String.valueOf(totalHarga));
            model.removeRow(selectedRow);
        }
    }//GEN-LAST:event_btnHapusBungaActionPerformed

    private void cbNamaPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNamaPemasokActionPerformed

    }//GEN-LAST:event_cbNamaPemasokActionPerformed

    private void CbBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbBungaActionPerformed

    }//GEN-LAST:event_CbBungaActionPerformed

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    private void txtTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalHargaActionPerformed

    private void btnTambahBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBungaActionPerformed
        String namaBunga = CbBunga.getSelectedItem().toString();
    int jumlah = (int) spJumlahBunga.getValue();

    try (Connection conn = KoneksiDB.getConnection()) {
        // Ambil harga bunga berdasarkan nama bunga
        String sql = "SELECT harga FROM Bunga WHERE nama_bunga = ?";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, namaBunga);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    double harga = rs.getDouble("harga");
                    double subtotal = harga * jumlah;

                    // Masukkan data ke JTable
                    DefaultTableModel model = (DefaultTableModel) tblPesanan.getModel();
                    model.addRow(new Object[]{null, cbNamaPemasok.getSelectedItem().toString(), txtTanggal.getText(), namaBunga, jumlah, harga, subtotal});

                    // Update total harga
                    double totalHarga = 0;
                    if (!txtTotalHarga.getText().isEmpty()) {
                        try {
                            totalHarga = Double.parseDouble(txtTotalHarga.getText());
                        } catch (NumberFormatException e) {
                            totalHarga = 0; // Jika teks tidak bisa di-parse, anggap sebagai 0
                        }
                    }
                    totalHarga += subtotal;
                    txtTotalHarga.setText(String.valueOf(totalHarga));
                }
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnTambahBungaActionPerformed

    private void btnSimpanPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPembelianActionPerformed
       Connection conn = null;
    try {
        conn = KoneksiDB.getConnection();
        conn.setAutoCommit(false); // Nonaktifkan auto-commit

        // Validasi input
        if (cbNamaPemasok.getSelectedItem() == null || txtTanggal.getText().isEmpty() || txtTotalHarga.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap lengkapi semua data.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Konversi tanggal
        LocalDate tanggal = LocalDate.parse(txtTanggal.getText(), DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        java.sql.Date sqlTanggal = java.sql.Date.valueOf(tanggal);

        // 1. Simpan ke tabel Pembelian
        String sqlPembelian = "INSERT INTO pembelian (supplier_id, tanggal, total_harga) VALUES ((SELECT supplier_id FROM supplier WHERE nama_supplier = ?), ?, ?)";
        PreparedStatement psPembelian = conn.prepareStatement(sqlPembelian, Statement.RETURN_GENERATED_KEYS);
        psPembelian.setString(1, cbNamaPemasok.getSelectedItem().toString());
        psPembelian.setDate(2, sqlTanggal);
        psPembelian.setDouble(3, Double.parseDouble(txtTotalHarga.getText()));

        psPembelian.executeUpdate();
        ResultSet rsPembelian = psPembelian.getGeneratedKeys();

        int pembelianId = 0;
        if (rsPembelian.next()) {
            pembelianId = rsPembelian.getInt(1); // Ambil pembelian_id yang dihasilkan
        }

        // 2. Simpan ke tabel Detail_Pembelian
        String sqlDetailPembelian = "INSERT INTO detail_pembelian (pembelian_id, bunga_id, jumlah, subtotal) " +
                            "VALUES (?, (SELECT bunga_id FROM bunga WHERE nama_bunga = ?), ?, ?)";
PreparedStatement psDetailPembelian = conn.prepareStatement(sqlDetailPembelian);

DefaultTableModel model = (DefaultTableModel) tblPesanan.getModel();
for (int i = 0; i < model.getRowCount(); i++) {
    // Ambil data dari tabel pesanan
    String namaBunga = model.getValueAt(i, 3).toString(); // Nama bunga dari kolom tabel
    int jumlah = Integer.parseInt(model.getValueAt(i, 4).toString()); // Jumlah bunga
    double subtotal = Double.parseDouble(model.getValueAt(i, 6).toString()); // Subtotal bunga

    // Set parameter untuk query
    psDetailPembelian.setInt(1, pembelianId); // pembelian_id
    psDetailPembelian.setString(2, namaBunga); // bunga_id berdasarkan nama bunga
    psDetailPembelian.setInt(3, jumlah); // jumlah bunga
    psDetailPembelian.setDouble(4, subtotal); // subtotal bunga

    psDetailPembelian.addBatch(); // Tambahkan ke batch eksekusi
}

// Eksekusi batch untuk menyimpan data detail pembelian
psDetailPembelian.executeBatch();
        // 3. Commit transaksi
        conn.commit();
        JOptionPane.showMessageDialog(this, "Pembelian berhasil disimpan.", "Success", JOptionPane.INFORMATION_MESSAGE);

    } catch (SQLException e) {
        if (conn != null) {
            try {
                conn.rollback(); // Rollback jika ada error
            } catch (SQLException rollbackEx) {
                rollbackEx.printStackTrace();
            }
        }
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        if (conn != null) {
            try {
                conn.setAutoCommit(true); // Aktifkan kembali auto-commit
                conn.close(); // Tutup koneksi
            } catch (SQLException closeEx) {
                closeEx.printStackTrace();
            }
        }
    }
    }//GEN-LAST:event_btnSimpanPembelianActionPerformed

    private void btnBatalPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalPembelianActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblPesanan.getModel();
        model.setRowCount(0); // Clear all rows
        txtTanggal.setText("");
        cbNamaPemasok.setSelectedIndex(0);
        txtTotalHarga.setText("");
    }//GEN-LAST:event_btnBatalPembelianActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Dashboard().setVisible(true);  // Membuka kelas Dashboard
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed
private void populateComboBoxBunga() {
    try (Connection conn = KoneksiDB.getConnection()) {
        String sql = "SELECT nama_bunga FROM Bunga";
        try (PreparedStatement ps = conn.prepareStatement(sql); 
             ResultSet rs = ps.executeQuery()) {

            // Clear existing items
            CbBunga.removeAllItems();

            // Add items to combo box
            while (rs.next()) {
                String namaBunga = rs.getString("nama_bunga");
                CbBunga.addItem(namaBunga); // Menambahkan nama bunga ke JComboBox
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
private void populateComboBoxPemasok() {
    try (Connection conn = KoneksiDB.getConnection()) {
        String sql = "SELECT nama_supplier FROM Supplier";
        try (PreparedStatement ps = conn.prepareStatement(sql); 
             ResultSet rs = ps.executeQuery()) {

            // Clear existing items
            cbNamaPemasok.removeAllItems();

            // Add items to combo box
            while (rs.next()) {
                String namaPemasok = rs.getString("nama_supplier");
                cbNamaPemasok.addItem(namaPemasok); // Menambahkan nama pemasok ke JComboBox
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
private void setTanggalOtomatis() {
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Format tanggal (YYYY-MM-DD)
    String tanggalSekarang = sdf.format(new Date()); // Mendapatkan tanggal hari ini
    txtTanggal.setText(tanggalSekarang); // Set ke JTextField txtTanggal
}
private void loadDataPembelian() {
    DefaultTableModel model = (DefaultTableModel) TblPembelian.getModel();
    model.setRowCount(0); // Bersihkan tabel sebelum menambahkan data

    String sql = "SELECT pembelian_id, supplier_id, tanggal, total_harga FROM pembelian";

    try (Connection conn = KoneksiDB.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            int pembelianId = rs.getInt("pembelian_id");
            int supplierId = rs.getInt("supplier_id");
            Date tanggal = rs.getDate("tanggal");
            double totalHarga = rs.getDouble("total_harga");

            model.addRow(new Object[]{pembelianId, supplierId, tanggal, totalHarga});
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal memuat data pembelian: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beli_Stock_Bunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beli_Stock_Bunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beli_Stock_Bunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beli_Stock_Bunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beli_Stock_Bunga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbBunga;
    private javax.swing.JTable TblPembelian;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBatalPembelian;
    private javax.swing.JButton btnHapusBunga;
    private javax.swing.JButton btnSimpanPembelian;
    private javax.swing.JButton btnTambahBunga;
    private javax.swing.JComboBox<String> cbNamaPemasok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spJumlahBunga;
    private javax.swing.JTable tblPesanan;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTotalHarga;
    // End of variables declaration//GEN-END:variables
}
