/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package percobaan9;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author ferdian
 */
public class Dashboard extends javax.swing.JFrame {
    private String namaPegawai;
    private String jabatanPegawai;

    // Konstruktor dengan parameter nama dan jabatan
    public Dashboard() {
        initComponents();
        tampilkanDataLogin();
        showTime();
        loadDataToTable(); 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProfil = new javax.swing.JButton();
        btnIsiStok = new javax.swing.JButton();
        btnEditCustomer = new javax.swing.JButton();
        btnPemesanan = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnLog_Out = new javax.swing.JButton();
        txtNama_Pegawai = new javax.swing.JTextField();
        txtJabatan = new javax.swing.JTextField();
        btnSupliyer = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataPenjualan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnProfil.setText("Profil");
        btnProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilActionPerformed(evt);
            }
        });

        btnIsiStok.setText("isi stok");
        btnIsiStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsiStokActionPerformed(evt);
            }
        });

        btnEditCustomer.setText("Customer");
        btnEditCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCustomerActionPerformed(evt);
            }
        });

        btnPemesanan.setText("Pemesanan");
        btnPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemesananActionPerformed(evt);
            }
        });

        btnLaporan.setText("Laporan");
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        btnLog_Out.setText("Log Out");
        btnLog_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLog_OutActionPerformed(evt);
            }
        });

        txtNama_Pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNama_PegawaiActionPerformed(evt);
            }
        });

        txtJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJabatanActionPerformed(evt);
            }
        });

        btnSupliyer.setText("Supliyer");
        btnSupliyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupliyerActionPerformed(evt);
            }
        });

        lblDate.setText("Date");

        lblTime.setText("Time");

        DataPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tanggal", "Jenis Transaksi", "Jumlah", "Deskripsi", "Saldo"
            }
        ));
        jScrollPane1.setViewportView(DataPenjualan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIsiStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSupliyer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNama_Pegawai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJabatan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 438, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTime, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(60, 60, 60))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLog_Out)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama_Pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPemesanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIsiStok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLaporan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSupliyer)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLog_Out)
                        .addGap(9, 9, 9))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilActionPerformed
      new Profil().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnProfilActionPerformed

    private void btnPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemesananActionPerformed
        new Pembelian().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnPemesananActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
    new Laporan_Keuangan().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnLog_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLog_OutActionPerformed
       int confirm = JOptionPane.showConfirmDialog(this, "Anda yakin ingin keluar?", "Log Out", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_btnLog_OutActionPerformed

    private void txtNama_PegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNama_PegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNama_PegawaiActionPerformed

    private void txtJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJabatanActionPerformed

    private void btnEditCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCustomerActionPerformed
     new FrameCustomer().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnEditCustomerActionPerformed

    private void btnIsiStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsiStokActionPerformed
      new Beli_Stock_Bunga().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnIsiStokActionPerformed

    private void btnSupliyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupliyerActionPerformed
       new Supliyer().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnSupliyerActionPerformed
 private void showTime(){
     
        Timer timer=new Timer(1000, new ActionListener(){
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat sdf=new SimpleDateFormat("EEEE, dd MMMM yyyy");
                SimpleDateFormat sdf2=new SimpleDateFormat("HH:mm:ss");
                String currentDate=sdf.format(new Date());
                String currentTime=sdf2.format(new Date());
                lblDate.setText(currentDate);
                lblTime.setText(currentTime);
            }
        });
        timer.start();
    }
 public void updateDashboardInfo(String nama, String jabatan) {
    this.namaPegawai = nama;
    this.jabatanPegawai = jabatan;
    txtNama_Pegawai.setText(namaPegawai);
    txtJabatan.setText(jabatanPegawai);
}
 private void tampilkanDataLogin() {
        // Ambil data dari UserSession
        String nama = UserSession.getNamaLengkap();
        String jabatan = UserSession.getJabatan();

        // Tampilkan data di label
        txtNama_Pegawai.setText("" + nama);
        txtJabatan.setText("" + jabatan);
    }
 public void loadDataToTable() {
    // SQL query untuk mengambil data dari tabel laporan_keuangan
    String query = "SELECT * FROM laporan_keuangan";

    try (Connection conn = KoneksiDB.getConnection();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(query)) {

        // Model untuk tabel DataPenjualan
        DefaultTableModel model = (DefaultTableModel) DataPenjualan.getModel();

        // Kosongkan tabel sebelum menambahkan data baru
        model.setRowCount(0);

        // Ambil data dari ResultSet dan tambahkan ke dalam model tabel
        while (rs.next()) {
            int id = rs.getInt("id");
            Date tanggal = rs.getDate("tanggal");
            String jenisTransaksi = rs.getString("jenis_transaksi");
            double jumlah = rs.getDouble("jumlah");
            String deskripsi = rs.getString("deskripsi");
            double saldo = rs.getDouble("saldo");

            // Tambahkan data ke dalam baris tabel
            model.addRow(new Object[]{id, tanggal, jenisTransaksi, jumlah, deskripsi, saldo});
        }

    } catch (SQLException e) {
        // Menangani exception jika terjadi error pada query atau koneksi
        JOptionPane.showMessageDialog(this, "Gagal mengambil data dari database.", "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
 
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DataPenjualan;
    private javax.swing.JButton btnEditCustomer;
    private javax.swing.JButton btnIsiStok;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLog_Out;
    private javax.swing.JButton btnPemesanan;
    private javax.swing.JButton btnProfil;
    private javax.swing.JButton btnSupliyer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtJabatan;
    private javax.swing.JTextField txtNama_Pegawai;
    // End of variables declaration//GEN-END:variables
}
